site_name: Walter
repo_url: https://github.com/jochenalt/Walter
edit_uri: edit/master/docs
repo_name: Walter
repo_authorr: 'Jochen Alt'
site_description: Walter a vintage robot Arm 
pages:
    - 'Home - Walter?!': 'index.md'
    - 'Construction - How is Walter built?': 'Construction.md'
    - 'Trajectory - How does Walter move?': 'Trajectory.md'
    - 'Kinematics - How are angles computed?': 'Kinematics.md'
    - 'Webserver - Where are trajectories executed?': 'Webserver.md'
    - 'Cortex - How are motors controlled?': 'Cortex.md'
    - 'Control Cabinet - GBR style': 'Control-Cabinet.md'
    - 'Bill of Material - What is Walter made of?': 'Bill-of-Material.md'
    - 'Gallery - Selfies': 'Gallery.md'
    - 'Sources - C++ Code, CAD models, FAQ, etc.': 'Sources.md'
